name: Validate markdown

on:
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  markdown-lint:
    name: Lint markdown files
    runs-on: ubuntu-latest
    # Checks markdown syntax and formatting
    steps:
    - uses: actions/checkout@v4

    - name: Run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@v20
      continue-on-error: false
      id: markdown-lint
      with:
        globs: '**/*.md'
        config: '.markdownlint.jsonc'
    
    - name: Report markdown lint results
      if: steps.markdown-lint.outcome == 'failure'
      run: |
        echo "::warning::Markdown formatting issues found. Please review the linting results above and consider fixing formatting inconsistencies for better readability."

  markdown-link-check:
    name: Check markdown links
    runs-on: ubuntu-latest
    # check out the latest version of the code
    steps:
    - uses: actions/checkout@v4

    # Checks the status of hyperlinks in .md files in verbose mode
    - name: Check links
      uses: tcort/github-action-markdown-link-check@v1
      continue-on-error: true
      id: link-check
      with:
        use-quiet-mode: 'yes'          # Only show broken links
        use-verbose-mode: 'yes'
        check-modified-files-only: 'no' # Check all files
        
    - name: Report link check results
      if: steps.link-check.outcome == 'failure'
      run: |
        echo "::warning::Some markdown links are broken. Please review the link check results above."

  spell-check:
    name: Spell check
    runs-on: ubuntu-latest
    # Checks spelling in markdown files
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install cSpell
      run: npm install -g cspell

    - name: Run cSpell
      continue-on-error: false
      id: spell-check
      run: cspell "**/*.md" --no-progress --no-summary

    - name: Report spell check results
      if: steps.spell-check.outcome == 'failure'
      run: |
        echo "::warning::Spelling issues found. Please review the spell check results above and consider fixing typos or adding legitimate words to cspell.json."
