name: Validate markdown

on:
  workflow_dispatch:  # Manual trigger only
  push:              # Run on push to any branch
    branches: ['**']

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    # Checks markdown syntax and formatting
    steps:
    - uses: actions/checkout@v4

    - name: Run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@v20
      continue-on-error: true
      id: markdown-lint
      with:
        globs: |
          **/*.md
          !SUPPORT.md
          !SECURITY.md
          !CODE_OF_CONDUCT.md
        config: '.markdownlint.jsonc'
    
    - name: Report markdown lint results
      if: steps.markdown-lint.outcome == 'failure'
      run: |
        echo "::warning::Markdown formatting issues found. Please review the linting results above and consider fixing formatting inconsistencies for better readability."

  markdown-link-check:
    runs-on: ubuntu-latest
    # check out the latest version of the code
    steps:
    - uses: actions/checkout@v4

    # Checks the status of hyperlinks in .md files in verbose mode
    - name: Check links
      uses: tcort/github-action-markdown-link-check@v1
      continue-on-error: true
      id: link-check
      with:
        use-quiet-mode: 'yes'          # Only show broken links
        use-verbose-mode: 'yes'
        check-modified-files-only: 'no' # Check all files
        
    - name: Report link check results
      if: steps.link-check.outcome == 'failure'
      run: |
        echo "::warning::Some markdown links are broken. Please review the link check results above."
